services:
  mongodb:
    image: mongo:7
    container_name: electronics-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: electronics
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: runtime
    image: ahceneaiti/electronics-api:1.0
    container_name: electronics-api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: local_compose_secret
      MONGODB_URL: "mongodb://root:root@mongodb:27017/?authSource=admin"
      MONGODB_DB: electronics
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
