apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: electronics-api
  namespace: electronics
  labels:
    app: electronics-api
spec:
  ingressClassName: nginx
  rules:
    - host: electronics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: electronics-api
                port:
                  number: 80
