# DEMO uniquement. En prod : SealedSecrets / External Secrets / SOPS.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: electronics
  labels:
    app: mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: S3cureChangeMe
