apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: electronics
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # kind fournit la StorageClass "standard" (rancher local-path) par defaut.
